# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94dbaf5ae00c9ffbacca20fdcda1a40ed40b71b2ee8ef09bdc2e978e9784be6333b9557a4748f071e5a67f5d822b8d9a4bfc29e19571f57e069a1c41498be921

test:
  secret_key_base: df8171e69ccce35f612457116ddb4c89d1a5a0d7003f0213552e7cb6645af91f51eb26278b7e21f2707f9cdc34ebbd02dc3fbb58483094e071ce3cce2d77b32d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
